### ISSUE TITLE
Add v1 tag

### ISSUE THREAD

**Issue by koppor** [NBprojekt/gource-action#4]
When running the example config, I get

    Error: Unable to resolve action `NBprojekt/gource-action@v1`, unable to find version `v1`

The current tags do not list `v1`:

![grafik](https://user-images.githubusercontent.com/1366654/102146851-feaa6480-3e69-11eb-8d99-d5653045c96a.png)

I think, `v1.0.1` should be tagged as `v1`, too.

(See https://github.com/JabRef/jabref/pull/7193/ for the usage)

**Comment by NBprojekt** [comment]
Thank you for this hit.

For this actions I allways used the `@master` tag thats why I did not notice this issue.

This issue should be solved by the [v1 branch](https://github.com/NBprojekt/gource-action/tree/v1) and your expected syntax should work with the latest release [v1.0.1](https://github.com/NBprojekt/gource-action/releases/tag/v1.0.1).

**Comment by NBprojekt** [comment]
Feedback if this works for you would be great @koppor ✌️

**Comment by koppor** [comment]
Thank you for the quick action taken. Typically, there isn't a v1 branch, just a "moving" v1 tag.

I got "v1" out of your README.md, where I copied and pasted the minimal example to get the action running.

**Comment by NBprojekt** [comment]
IMHO, "moving tags" or "re tagging" is kinda hacky.

Therefor I found this interesting [issue](https://github.com/actions/toolkit/issues/214) and i wanted to try it out for some time using braches instead of moving tags.

Also note that noting chages for the use
> 
>Say v1 points to v1.0.0, and a new version v1.1.0 has been tagged. After successfully testing v1.1.0, v1 could simply be fast-forwarded to v1.1.0. There is no need to force anything, and from a user's perspective, everything remains the same, e.g.  
>using an action would still look like this:
>
>```uses: actions/custom-action@v1```

In this case you can still use: `uses: nbprojekt/gource-action@v1`
